development:
  adapter: postgresql
  database: railway-dev
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  encoding: utf8
  pool: 5

production:
  adapter: postgresql
  database: railway-pro
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  encoding: utf8
  pool: 5

test: &test
  adapter: postgresql
  database: railway-test
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  encoding: utf8
  pool: 5